
# 5.times do |i|
#   User.create(
#     name: "test#{i}",
#     email: "test#{i + 1}@test.com",
#     password: "aaaaaaaa",
#     role_id: 4,
#     gender: 1
#     )
# end

User.create(name: "システム管理者", email: "test1@test", password: "aaaaaaaa", password_confirmation: "aaaaaaaa", role_id: 1, gender: 1, birthday: "2021-05-08", address: "22", closest_station: "33", profile_hide: false, years_of_experience: 11, department_id: 1)

Role.create(name:"システム管理者")
Role.create(name:"管理者")
Role.create(name:"マネジャー")
Role.create(name:"一般")
Role.create(name:"営業")

SkillLevel.create(name:"始めたてor趣味(目安：１年未満)")
SkillLevel.create(name:"1人でできる(目安：１年以上)")
SkillLevel.create(name:"教えることができる(目安：３年以上)")
SkillLevel.create(name:"プロフェッショナル(目安：５年以上)")


SkillKind.create(name:"プログラミング言語")
SkillKind.create(name:"フレームワーク・ライブラリ")
SkillKind.create(name:"データベース")
SkillKind.create(name:"開発工程")
SkillKind.create(name:"経験分野")
SkillKind.create(name:"経験分野詳細")
SkillKind.create(name:"開発環境(OSなど)")
SkillKind.create(name:"Webサーバー")
SkillKind.create(name:"クラウドプラットフォーム")
SkillKind.create(name:"インフラ")
SkillKind.create(name:"マネジメント経験")
SkillKind.create(name:"開発支援ツール")
SkillKind.create(name:"IDE・Editor")
SkillKind.create(name:"バージョン管理ツール")
SkillKind.create(name:"言語のバージョン管理ツール")
SkillKind.create(name:"言語のパッケージ管理ツール")
SkillKind.create(name:"OSのパッケージ管理ツール")
SkillKind.create(name:"開発手法")
SkillKind.create(name:"資格")

# プログラミング言語
Skill.create(name:"HTML", skill_kind_id:1)
Skill.create(name:"CSS", skill_kind_id:1)
Skill.create(name:"Java", skill_kind_id:1)
Skill.create(name:"Java Script", skill_kind_id:1)
Skill.create(name:"TypeScript", skill_kind_id:1)
Skill.create(name:"PHP", skill_kind_id:1)
Skill.create(name:"Ruby", skill_kind_id:1)
Skill.create(name:"Python", skill_kind_id:1)
Skill.create(name:"Swift", skill_kind_id:1)
Skill.create(name:"VB", skill_kind_id:1)
Skill.create(name:"VB.NET", skill_kind_id:1)
Skill.create(name:"VBA", skill_kind_id:1)
Skill.create(name:"C#", skill_kind_id:1)
Skill.create(name:"C", skill_kind_id:1)
Skill.create(name:"C++", skill_kind_id:1)
Skill.create(name:"Objective-C", skill_kind_id:1)
Skill.create(name:"Perl", skill_kind_id:1)
Skill.create(name:"kotlin", skill_kind_id:1)
Skill.create(name:"R言語", skill_kind_id:1)
Skill.create(name:"SQL", skill_kind_id:1)
Skill.create(name:"Scala", skill_kind_id:1)
Skill.create(name:"Go言語", skill_kind_id:1)
Skill.create(name:"Rust", skill_kind_id:1)
Skill.create(name:"Haskell", skill_kind_id:1)

# フレームワーク・ライブラリ
Skill.create(name:"BootStrap", skill_kind_id:2)
Skill.create(name:"Facebook Flow", skill_kind_id:2)
Skill.create(name:"Ajax", skill_kind_id:2)
Skill.create(name:"jQuery", skill_kind_id:2)
Skill.create(name:"Node", skill_kind_id:2)
Skill.create(name:"React", skill_kind_id:2)
Skill.create(name:"Vue", skill_kind_id:2)
Skill.create(name:"AngularJS", skill_kind_id:2)
Skill.create(name:"Datatables", skill_kind_id:2)
Skill.create(name:"Backbone", skill_kind_id:2)
Skill.create(name:"Spring Framework", skill_kind_id:2)
Skill.create(name:"Spring Boot", skill_kind_id:2)
Skill.create(name:"JSF（JavaServer Faces）", skill_kind_id:2)
Skill.create(name:"Play Framework", skill_kind_id:2)
Skill.create(name:"Apache Struts", skill_kind_id:2)
Skill.create(name:"Javalin", skill_kind_id:2)
Skill.create(name:"Ruby on Rails", skill_kind_id:2)
Skill.create(name:"WEBrick", skill_kind_id:2)
Skill.create(name:"Django", skill_kind_id:2)
Skill.create(name:"Flask", skill_kind_id:2)
Skill.create(name:"Bottle", skill_kind_id:2)
Skill.create(name:"Tornado", skill_kind_id:2)
Skill.create(name:"web2Py", skill_kind_id:2)
Skill.create(name:".net Framework", skill_kind_id:2)
Skill.create(name:".NET Core", skill_kind_id:2)
Skill.create(name:"ASP.NET Core MVC", skill_kind_id:2)
Skill.create(name:"ASP.NET Core Razor Pages", skill_kind_id:2)
Skill.create(name:"ASP.NET MVC", skill_kind_id:2)
Skill.create(name:"ASP.NET WebForms", skill_kind_id:2)
Skill.create(name:"perfect", skill_kind_id:2)
Skill.create(name:"Swifton", skill_kind_id:2)
Skill.create(name:"Slimane", skill_kind_id:2)
Skill.create(name:"Kitura", skill_kind_id:2)
Skill.create(name:"Express", skill_kind_id:2)
Skill.create(name:"Vapor", skill_kind_id:2)
Skill.create(name:"HTTPSwiftServer", skill_kind_id:2)
Skill.create(name:"React Native", skill_kind_id:2)
Skill.create(name:"Spring Framework", skill_kind_id:2)
Skill.create(name:"Spring Boot", skill_kind_id:2)
Skill.create(name:"wasabi", skill_kind_id:2)
Skill.create(name:"Jooby", skill_kind_id:2)
Skill.create(name:"ktor", skill_kind_id:2)
Skill.create(name:"Javalin", skill_kind_id:2)
Skill.create(name:"Mojolicios", skill_kind_id:2)
Skill.create(name:"Dancer", skill_kind_id:2)
Skill.create(name:"Catalyst", skill_kind_id:2)
Skill.create(name:"Amon2", skill_kind_id:2)
Skill.create(name:"TripletaiL", skill_kind_id:2)
Skill.create(name:"Ark", skill_kind_id:2)
Skill.create(name:"Seasar2", skill_kind_id:2)
Skill.create(name:"Hibernate", skill_kind_id:2)
Skill.create(name:"CakePHP", skill_kind_id:2)
Skill.create(name:"Unity", skill_kind_id:2)
Skill.create(name:"Pylons", skill_kind_id:2)
Skill.create(name:"ngCore", skill_kind_id:2)
Skill.create(name:"Unreal Engine", skill_kind_id:2)
Skill.create(name:"FuelPHP", skill_kind_id:2)
Skill.create(name:"Zend Framework", skill_kind_id:2)
Skill.create(name:"prototype.js", skill_kind_id:2)
Skill.create(name:"DirectX", skill_kind_id:2)
Skill.create(name:"OpenGL", skill_kind_id:2)
Skill.create(name:"Android SDK", skill_kind_id:2)
Skill.create(name:"iOS SDK", skill_kind_id:2)
Skill.create(name:"Smarty", skill_kind_id:2)
Skill.create(name:"MyBatis", skill_kind_id:2)
Skill.create(name:"Play Framework", skill_kind_id:2)
Skill.create(name:"Laravel", skill_kind_id:2)
Skill.create(name:"Java EE", skill_kind_id:2)
Skill.create(name:"Slim", skill_kind_id:2)
Skill.create(name:"Sinatra", skill_kind_id:2)
Skill.create(name:"Catalyst", skill_kind_id:2)
Skill.create(name:"Backbone.js", skill_kind_id:2)
Skill.create(name:"Ember.js", skill_kind_id:2)
Skill.create(name:"Knockout.js", skill_kind_id:2)
Skill.create(name:"Riot.js", skill_kind_id:2)
Skill.create(name:"Echo", skill_kind_id:2)
Skill.create(name:"Revel", skill_kind_id:2)
Skill.create(name:"Foundation", skill_kind_id:2)
Skill.create(name:"TensorFlow", skill_kind_id:2)
Skill.create(name:"Chainer", skill_kind_id:2)
Skill.create(name:"Caffe", skill_kind_id:2)
Skill.create(name:"Express", skill_kind_id:2)
Skill.create(name:"Flutter", skill_kind_id:2)
Skill.create(name:"Xamarin", skill_kind_id:2)
Skill.create(name:"Nuxt.js", skill_kind_id:2)

# データベース
Skill.create(name:"MySQL", skill_kind_id:3)
Skill.create(name:"Microsoft SQL Server", skill_kind_id:3)
Skill.create(name:"PostgreSQL", skill_kind_id:3)
Skill.create(name:"Microsoft Access", skill_kind_id:3)
Skill.create(name:"Oracle Database", skill_kind_id:3)
Skill.create(name:"SQLite", skill_kind_id:3)
Skill.create(name:"MongoDB", skill_kind_id:3)
Skill.create(name:"Redis", skill_kind_id:3)

# 開発工程
Skill.create(name:"プログラムコーディング", skill_kind_id:4)
Skill.create(name:"システム設計", skill_kind_id:4)
Skill.create(name:"保守、追加開発", skill_kind_id:4)
Skill.create(name:"プロジェクトマネジメント", skill_kind_id:4)
Skill.create(name:"インフラ設計", skill_kind_id:4)
Skill.create(name:"インフラ構築", skill_kind_id:4)
Skill.create(name:"新規開発の企画", skill_kind_id:4)
Skill.create(name:"要件定義", skill_kind_id:4)
Skill.create(name:"テスト", skill_kind_id:4)
Skill.create(name:"研究開発", skill_kind_id:4)

# 経験分野
Skill.create(name:"Web開発（サーバサイドエンジニア）", skill_kind_id:5)
Skill.create(name:"Web開発（フロントエンドエンジニア）", skill_kind_id:5)
Skill.create(name:"スマートフォンアプリ開発", skill_kind_id:5)
Skill.create(name:"フィーチャーフォンアプリ開発", skill_kind_id:5)
Skill.create(name:"制御組込み系開発", skill_kind_id:5)
Skill.create(name:"OS・ミドルウェア開発", skill_kind_id:5)
Skill.create(name:"研究開発（画像処理,自然言語処理,機械学習,AIなど）", skill_kind_id:5)
Skill.create(name:"コンシューマーゲーム開発", skill_kind_id:5)
Skill.create(name:"デスクトップアプリ開発（Windows,Macなど）", skill_kind_id:5)
Skill.create(name:"汎用系開発業務（金融,保険,証券など）", skill_kind_id:5)
Skill.create(name:"セキュリティソフトウェア開発", skill_kind_id:5)

# 経験分野詳細
Skill.create(name:"B2C", skill_kind_id:6)
Skill.create(name:"B2B", skill_kind_id:6)
Skill.create(name:"C2C", skill_kind_id:6)
Skill.create(name:"WEBサイト、CMS", skill_kind_id:6)
Skill.create(name:"ソーシャルメディア", skill_kind_id:6)
Skill.create(name:"ポータルサイト", skill_kind_id:6)
Skill.create(name:"EC", skill_kind_id:6)
Skill.create(name:"ソーシャルゲーム", skill_kind_id:6)
Skill.create(name:"コンシューマーゲーム", skill_kind_id:6)
Skill.create(name:"業務システム/パッケージ", skill_kind_id:6)
Skill.create(name:"金融/保険", skill_kind_id:6)
Skill.create(name:"スマートフォンアプリ", skill_kind_id:6)
Skill.create(name:"フィーチャーフォンアプリ", skill_kind_id:6)
Skill.create(name:"スマートフォンサイト", skill_kind_id:6)
Skill.create(name:"フィーチャーフォンサイト", skill_kind_id:6)
Skill.create(name:"アドテク", skill_kind_id:6)
Skill.create(name:"リサーチ、解析", skill_kind_id:6)
Skill.create(name:"ミドルウェア", skill_kind_id:6)
Skill.create(name:"SaaS", skill_kind_id:6)
Skill.create(name:"ASP", skill_kind_id:6)
Skill.create(name:"Win/Macアプリケーション", skill_kind_id:6)
Skill.create(name:"自然言語処理", skill_kind_id:6)
Skill.create(name:"画像処理", skill_kind_id:6)
Skill.create(name:"機械学習", skill_kind_id:6)
Skill.create(name:"AI", skill_kind_id:6)
Skill.create(name:"データベースの設計、チューニング", skill_kind_id:6)
Skill.create(name:"ネットワーク設計", skill_kind_id:6)
Skill.create(name:"GUIデザイン開発", skill_kind_id:6)
Skill.create(name:"C2B", skill_kind_id:6)
Skill.create(name:"受託開発（自社内開発）", skill_kind_id:6)
Skill.create(name:"受託開発（社外常駐）", skill_kind_id:6)
Skill.create(name:"オンラインゲーム", skill_kind_id:6)
Skill.create(name:"ハードウェア制御・組込み", skill_kind_id:6)
Skill.create(name:"FinTech", skill_kind_id:6)
Skill.create(name:"モビリティ関連（自動運転、交通関連）", skill_kind_id:6)
Skill.create(name:"ブロックチェーン", skill_kind_id:6)
Skill.create(name:"動画", skill_kind_id:6)
Skill.create(name:"IoT", skill_kind_id:6)
Skill.create(name:"大規模", skill_kind_id:6)

# 開発環境(OSなど)
Skill.create(name:"Cent OS", skill_kind_id:7)
Skill.create(name:"Debian", skill_kind_id:7)
Skill.create(name:"Red Hat", skill_kind_id:7)
Skill.create(name:"Mac OS X", skill_kind_id:7)
Skill.create(name:"Windows", skill_kind_id:7)
Skill.create(name:"Vim", skill_kind_id:7)
Skill.create(name:"Linux", skill_kind_id:7)
Skill.create(name:"UNIX", skill_kind_id:7)
Skill.create(name:"WordPress", skill_kind_id:7)
Skill.create(name:"Solaris", skill_kind_id:7)
Skill.create(name:"Windows Server", skill_kind_id:7)
Skill.create(name:"AIX", skill_kind_id:7)
Skill.create(name:"HP-UX", skill_kind_id:7)

# Webサーバー
Skill.create(name:"Apache", skill_kind_id:8)
Skill.create(name:"Nginx", skill_kind_id:8)
Skill.create(name:"Tomcat", skill_kind_id:8)
Skill.create(name:"IIS", skill_kind_id:8)
Skill.create(name:"Unicorn", skill_kind_id:8)
Skill.create(name:"Puma", skill_kind_id:8)
Skill.create(name:"Passenger", skill_kind_id:8)
Skill.create(name:"Zope", skill_kind_id:8)

# クラウドプラットフォーム
Skill.create(name:"Amazon Web Service", skill_kind_id:9)
Skill.create(name:"Microsoft Azure", skill_kind_id:9)
Skill.create(name:"Google Cloud Platform", skill_kind_id:9)
Skill.create(name:"Firebase", skill_kind_id:9)
Skill.create(name:"Heroku", skill_kind_id:9)
Skill.create(name:"Salesforce", skill_kind_id:9)
Skill.create(name:"Google App Engine", skill_kind_id:9)

# インフラ
Skill.create(name:"Docker", skill_kind_id:10)
Skill.create(name:"Kubernetes", skill_kind_id:10)
Skill.create(name:"Amazon ECS", skill_kind_id:10)

# マネジメント経験
Skill.create(name:"メンバー育成（OJT、メンター）", skill_kind_id:11)
Skill.create(name:"メンバーマネジメント（目標設計、評価）", skill_kind_id:11)
Skill.create(name:"予実管理", skill_kind_id:11)
Skill.create(name:"採用", skill_kind_id:11)
Skill.create(name:"チームの指針策定と牽引", skill_kind_id:11)
Skill.create(name:"ラインマネジメント", skill_kind_id:11)
Skill.create(name:"CTO／技術責任者", skill_kind_id:11)

# 開発支援ツール
Skill.create(name:"Redmine", skill_kind_id:12)
Skill.create(name:"JIRA", skill_kind_id:12)
Skill.create(name:"Backlog", skill_kind_id:12)
Skill.create(name:"Jenkins", skill_kind_id:12)
Skill.create(name:"Trac", skill_kind_id:12)
Skill.create(name:"Pivotal Tracker", skill_kind_id:12)
Skill.create(name:"Basecamp ", skill_kind_id:12)
Skill.create(name:"New Relic", skill_kind_id:12)
Skill.create(name:"Circle CI", skill_kind_id:12)
Skill.create(name:"Travis CI", skill_kind_id:12)
Skill.create(name:"Jest", skill_kind_id:12)
Skill.create(name:"Katalon Studio", skill_kind_id:12)
Skill.create(name:"Watir", skill_kind_id:12)
Skill.create(name:"Mocha", skill_kind_id:12)
Skill.create(name:"Sinon.js", skill_kind_id:12)
Skill.create(name:"Karma", skill_kind_id:12)
Skill.create(name:"Selenium WebDriver", skill_kind_id:12)
Skill.create(name:"Tricentis Tosca", skill_kind_id:12)
Skill.create(name:"Unified Functional Testing", skill_kind_id:12)
Skill.create(name:"Appium", skill_kind_id:12)
Skill.create(name:"Apache Jmeter", skill_kind_id:12)
Skill.create(name:"AVA", skill_kind_id:12)
Skill.create(name:"Rollbar", skill_kind_id:12)
Skill.create(name:"Sentry", skill_kind_id:12)
Skill.create(name:"PagerDuty", skill_kind_id:12)
Skill.create(name:"digdag", skill_kind_id:12)
Skill.create(name:"Grafana", skill_kind_id:12)
Skill.create(name:"Tableau", skill_kind_id:12)
Skill.create(name:"Redash", skill_kind_id:12)

# バージョン管理
Skill.create(name:"Git", skill_kind_id:13)
Skill.create(name:"GitHub", skill_kind_id:13)
Skill.create(name:"GitLab", skill_kind_id:13)
Skill.create(name:"GitBucket", skill_kind_id:13)
Skill.create(name:"BitBucket", skill_kind_id:13)
Skill.create(name:"mercurial ", skill_kind_id:13)
Skill.create(name:"bazaar ", skill_kind_id:13)
Skill.create(name:"Subversion", skill_kind_id:13)
Skill.create(name:"CVS", skill_kind_id:13)

# IDE・Editor
Skill.create(name:"Eclipse", skill_kind_id:14)
Skill.create(name:"Visual Studio", skill_kind_id:14)
Skill.create(name:"Visual Studio Code", skill_kind_id:14)
Skill.create(name:"Xcode", skill_kind_id:14)
Skill.create(name:"PyCharm", skill_kind_id:14)
Skill.create(name:"IntelliJ IDEA", skill_kind_id:14)
Skill.create(name:"Atom", skill_kind_id:14)
Skill.create(name:"WebStorm", skill_kind_id:14)
Skill.create(name:"Rubymine", skill_kind_id:14)
Skill.create(name:"NetBeans", skill_kind_id:14)
Skill.create(name:"Cloud9", skill_kind_id:14)
Skill.create(name:"Emacs", skill_kind_id:14)

# 言語のバージョン管理ツール
Skill.create(name:"ndenv (Node.js)", skill_kind_id:15)
Skill.create(name:"nodenv (Node.js)", skill_kind_id:15)
Skill.create(name:"rbenv (Ruby)", skill_kind_id:15)
Skill.create(name:"phpenv (PHP)", skill_kind_id:15)
Skill.create(name:"pyenv (Python)", skill_kind_id:15)
Skill.create(name:"plenv (Perl)", skill_kind_id:15)
Skill.create(name:"jenv (Java)", skill_kind_id:15)
Skill.create(name:"scalaenv (Scala)", skill_kind_id:15)
Skill.create(name:"swiftenv (Swift)", skill_kind_id:15)
Skill.create(name:"goenv (Go言語)", skill_kind_id:15)
Skill.create(name:"nodebrew (Node.js)", skill_kind_id:15)
Skill.create(name:"phpbrew (PHP)", skill_kind_id:15)
Skill.create(name:"nvm (Node.js)", skill_kind_id:15)
Skill.create(name:"nodist (Node.js)", skill_kind_id:15)

# 言語のパッケージ管理ツール
Skill.create(name:"npm (Node.js)", skill_kind_id:16)
Skill.create(name:"yarn (Node.js)", skill_kind_id:16)
Skill.create(name:"gem (Ruby)", skill_kind_id:16)
Skill.create(name:"Composer (PHP)", skill_kind_id:16)
Skill.create(name:"pip (Python)", skill_kind_id:16)
Skill.create(name:"CPAN (Perl)", skill_kind_id:16)
Skill.create(name:"sbaz (Scala)", skill_kind_id:16)
Skill.create(name:"glide (Go言語)", skill_kind_id:16)

# OSのパッケージ管理ツール
Skill.create(name:"PackageManagemet (Windows)", skill_kind_id:17)
Skill.create(name:"Chocolatey (Windows)", skill_kind_id:17)
Skill.create(name:"MacPort (Mac)", skill_kind_id:17)
Skill.create(name:"Homebrew (Mac)", skill_kind_id:17)
Skill.create(name:"rpm (Linux RedHot系)", skill_kind_id:17)
Skill.create(name:"yum (Linux RedHot系)", skill_kind_id:17)
Skill.create(name:"deb (Linux Debian系)", skill_kind_id:17)
Skill.create(name:"apt-get (Linux Debian系)", skill_kind_id:17)
Skill.create(name:"Linuxbrew (Linux)", skill_kind_id:17)

# 開発手法
Skill.create(name:"オブジェクト指向", skill_kind_id:18)
Skill.create(name:"ウォーターフォール", skill_kind_id:18)
Skill.create(name:"アジャイル", skill_kind_id:18)
Skill.create(name:"スクラム", skill_kind_id:18)
Skill.create(name:"ペアプロ", skill_kind_id:18)
Skill.create(name:"テスト駆動開発", skill_kind_id:18)
Skill.create(name:"チケット駆動開発", skill_kind_id:18)
Skill.create(name:"プロトタイピング", skill_kind_id:18)
Skill.create(name:"コーディング規約あり", skill_kind_id:18)
Skill.create(name:"グローバルチーム（多国籍メンバー）", skill_kind_id:18)
Skill.create(name:"ドメイン駆動設計", skill_kind_id:18)

# 資格
Skill.create(name:"AWS - クラウドプラクティショナー", skill_kind_id:19)
Skill.create(name:"AWS - ソリューションアーキテクト", skill_kind_id:19)
Skill.create(name:"AWS - SysOpsアドミニストレイター", skill_kind_id:19)
Skill.create(name:"AWS - デベロッパー", skill_kind_id:19)
Skill.create(name:"AWS - ソリューションアーキテクト", skill_kind_id:19)
Skill.create(name:"AWS - DevOpsエンジニア", skill_kind_id:19)
Skill.create(name:"Azure - Fundamentals", skill_kind_id:19)
Skill.create(name:"Azure - 管理者アソシエイツ(Azure)", skill_kind_id:19)
Skill.create(name:"Azure - Developer アソシエイツ(Azure)", skill_kind_id:19)
Skill.create(name:"Azure - Security Engineer アソシエイツ(Azure)", skill_kind_id:19)
Skill.create(name:"Azure - DevOps Engineer Expert(Azure)", skill_kind_id:19)
Skill.create(name:"Azure - Solutions Architect Expert(Azure)", skill_kind_id:19)
Skill.create(name:"GCP - Cloud Engineer", skill_kind_id:19)
Skill.create(name:"GCP - Professional Cloud Architect", skill_kind_id:19)
Skill.create(name:"GCP - Professional Cloud Developer", skill_kind_id:19)
Skill.create(name:"GCP - Professional Data Engineer", skill_kind_id:19)
Skill.create(name:"GCP - Professional Cloud DevOps Engineer", skill_kind_id:19)
Skill.create(name:"GCP - Professional Cloud Security Engineer", skill_kind_id:19)
Skill.create(name:"GCP - Professional Cloud Network Engineer", skill_kind_id:19)
Skill.create(name:"GCP - Professional Collaboration Engineer", skill_kind_id:19)
Skill.create(name:"GCP - Professional Machine Learning Engineer", skill_kind_id:19)
Skill.create(name:"IPA - 基本情報処理試験", skill_kind_id:19)
Skill.create(name:"IPA - 応用情報処理試験", skill_kind_id:19)
Skill.create(name:"IPA - ネットワークスペシャリスト", skill_kind_id:19)
Skill.create(name:"IPA - データベーススペシャリスト", skill_kind_id:19)
Skill.create(name:"IPA - 情報セキュリティスペシャリスト", skill_kind_id:19)
Skill.create(name:"IPA - システムアーキテクト", skill_kind_id:19)
Skill.create(name:"IPA - プロジェクトマネージャ", skill_kind_id:19)
Skill.create(name:"IPA - ＩＴストラテジスト", skill_kind_id:19)
Skill.create(name:"IPA - システム監査技術者", skill_kind_id:19)
Skill.create(name:"IPA - プロジェクトマネージャ", skill_kind_id:19)
Skill.create(name:"LPIC - Level1", skill_kind_id:19)
Skill.create(name:"LPIC - Level2", skill_kind_id:19)
Skill.create(name:"LPIC - Level3", skill_kind_id:19)
Skill.create(name:"メンタルヘルスケアマネジメント Ⅲ種セルフケアコース", skill_kind_id:19)
Skill.create(name:"メンタルヘルスケアマネジメント Ⅱ種ラインケアコース", skill_kind_id:19)
Skill.create(name:"メンタルヘルスケアマネジメント Ⅰ種マスターケアコース", skill_kind_id:19)
Skill.create(name:"オラクルマスター - Bronze", skill_kind_id:19)
Skill.create(name:"オラクルマスター - Silver", skill_kind_id:19)
Skill.create(name:"オラクルマスター - Gold", skill_kind_id:19)
Skill.create(name:"オラクルマスター - Platinum", skill_kind_id:19)
Skill.create(name:"OCJP - Bronze", skill_kind_id:19)
Skill.create(name:"OCJP - Silver", skill_kind_id:19)
Skill.create(name:"OCJP - Gold", skill_kind_id:19)
Skill.create(name:"JSTQB", skill_kind_id:19)
Skill.create(name:"PMP(Project Management Professional）", skill_kind_id:19)
Skill.create(name:"ドットコムマスター", skill_kind_id:19)

# Authority.create(name:"ホーム")
# Authority.create(name:"従業員検索")
# Authority.create(name:"従業員詳細")
# Authority.create(name:"従業員編集")
# Authority.create(name:"マスタ編集")

# # RoleAuthorityLink.create(role_id:1,)



# 済


# Skill.create(name:"Java",kind_id:1)

# users = ["yamada", "abe", "tanaka", "yave", "kitani"]
# users.each_with_index do |user, i|
#   User.create(
#     name: "#{user}",
#     email: "test#{i + 1}@test.com",
#     password: "aaaaaaaa",
#     rols_id:4
#   )
# end